SELECT A.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER A
     JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
GROUP BY A.PRODUCT_ID, B.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC